version: "3.9"

services:
  postgis:
    image: kartoza/postgis:9.6-2.4
    environment:
      - POSTGRES_DBNAME=gis
      - POSTGRES_USER=user001
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"